[tasks.tfinit]
description = "Run Terraform init for managed work and fork repositories"
run = [
  "terraform -chdir=terraform/work-repositories init -backend-config=backend.hcl",
  "terraform -chdir=terraform/fork-repositories init -backend-config=backend.hcl"
]

[tasks."work:plan"]
description = "Run Terraform plan for managed working repositories"
run = ["terraform -chdir=terraform/work-repositories plan"]

[tasks."work:apply"]
description = "Run Terraform apply for managed working repositories"
run = ["terraform -chdir=terraform/work-repositories apply"]

[tasks."fork:plan"]
description = "Run Terraform plan for managed fork repositories"
run = ["terraform -chdir=terraform/fork-repositories plan"]

[tasks."fork:apply"]
description = "Run Terraform apply for managed fork repositories"
run = ["terraform -chdir=terraform/fork-repositories apply"]
